import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'km';
  setLanguage: (lang: 'en' | 'km') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    dashboard: 'Dashboard',
    patients: 'Patients',
    doctors: 'Doctors',
    medications: 'Medications',
    prescriptions: 'Prescriptions',

    // Common
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    contact: 'Contact',
    search: 'Search',
    print: 'Print',
    success: 'Success',
    error: 'Error',

    // Dashboard
    totalPatients: 'Total Patients',
    totalDoctors: 'Total Doctors',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',

    // Patients
    addPatient: 'Add Patient',
    patientName: 'Patient Name',
    age: 'Age',
    medicalHistory: 'Medical History',
    fullName: 'Full Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    gender: 'Gender',
    dateOfBirth: 'Date of Birth',
    address: 'Address',
    allRegisteredPatients: 'All Registered Patients',
    noPatientsFound: 'No patients found',
    getStartedPatient: 'Get started by adding your first patient.',
    addNewPatient: 'Add New Patient',
    editPatient: 'Edit Patient',
    patientInfoPrompt: "Enter the patient's information to create a new record.",
    selectGender: 'Select gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    pickDate: 'Pick a date',
    updatePatient: 'Update Patient',
    createPatient: 'Create Patient',
    patientUpdatedSuccess: 'Patient updated successfully',
    patientAddedSuccess: 'Patient added successfully',
    patientSaveFailed: 'Failed to save patient',
    patientDeletedSuccess: 'Patient deleted successfully',
    patientDeleteFailed: 'Failed to delete patient',
    confirmDeletePatient: 'Are you sure you want to delete this patient?',
    fetchPatientsFailed: 'Failed to fetch patients',
    loading: 'Loading...',
    actions: 'Actions',
    doctorImage: 'Doctor Image',
    noDoctorAssigned: 'No doctor assigned',
    patientNotFound: 'Patient Not Found',
    patientNotFoundDescription: 'The patient you are looking for does not exist or has been removed.',
    back: 'Back',
    overview: 'Overview',
    documents: 'Documents',
    noDescription: 'No description available',
    noAddress: 'No address provided',
    emergencyContact: 'Emergency Contact',
    noEmergencyContact: 'No emergency contact information',
    upcomingAppointments: 'Upcoming Appointments',
    noAppointments: 'No upcoming appointments',
    noMedicalHistory: 'No medical history recorded',
    assignedDoctor: 'Assigned Doctor',
    bloodType: 'Blood Type',
    selectBloodType: 'Select blood type',
    contactAndInsurance: 'Contact & Insurance',
    basicInfo: 'Basic Info',
    medical: 'Medical',
    descriptionPlaceholder: 'Brief description or notes about the patient',
    enterFullName: "Enter patient's full name",
    preferNotToSay: 'Prefer not to say',

    // Doctors
    addDoctor: 'Add Doctor',
    doctorName: 'Doctor Name',
    specialty: 'Specialty',
    editDoctor: 'Edit Doctor',
    doctorUpdated: 'Doctor updated successfully',
    doctorAdded: 'Doctor added successfully',
    doctorDeleted: 'Doctor deleted successfully',
    doctorFailedSave: 'Failed to save doctor',
    confirmDeleteDoctor: 'Are you sure you want to delete this doctor?',
    noDoctorsFound: 'No doctors found',

    // Medications
    addMedication: 'Add Medication',
    medicationName: 'Medication Name',
    dosage: 'Dosage',
    stockQuantity: 'Stock Quantity',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    medicationUpdatedSuccess: 'Medication updated successfully',
    medicationAddedSuccess: 'Medication added successfully',
    medicationSaveFailed: 'Failed to save medication',
    confirmDeleteMedication: 'Are you sure you want to delete this medication?',
    medicationDeletedSuccess: 'Medication deleted successfully',
    medicationDeleteFailed: 'Failed to delete medication',
    fetchMedicationsFailed: 'Failed to fetch medications',
    noMedicationsFound: 'No medications found',
    getStartedMedication: 'Get started by adding your first medication.',
    image: 'Image',
    uploadImage: 'Upload Image',
    // Added for Medications page form/dialog
    'medications.productName': 'Product Name',
    'medications.category': 'Category',
    'medications.selectCategory': 'Select category',
    'medications.other': 'Other',
    'medications.enterNewCategory': 'Enter new category',
    'medications.currentStock': 'Current Stock',
    'medications.unitPrice': 'Unit Price ($)',
    'medications.expiryDate': 'Expiry Date',
    'medications.productImage': 'Product Image',
    'medications.updateItem': 'Update Item',
    'medications.addItem': 'Add Item',
    // Added for Medications page UI
    'medications.inventoryTitle': 'Pharmacy Inventory',
    'medications.inventorySubtitle': 'Manage your medication stock efficiently',
    'medications.totalValue': 'Total Value',
    'medications.totalItems': 'Total Items',
    'medications.lowStock': 'Low Stock',
    'medications.outOfStock': 'Out of Stock',
    'medications.searchPlaceholder': 'Search by name, dosage, or SKU...',
    'medications.allCategories': 'All Categories',
    'medications.status': 'Status',
    'medications.allStatus': 'All Status',
    'medications.normalStock': 'Normal Stock',
    'medications.export': 'Export',
    'medications.editInventoryItem': 'Edit Inventory Item',
    'medications.addNewInventoryItem': 'Add New Inventory Item',
    'medications.updateDetails': 'Update the details for this medication.',
    'medications.fillDetails': 'Fill in the details to add a new medication to your inventory.',
    'medications.noItemsFound': 'No items found',
    'medications.noInventoryItems': 'No inventory items',
    'medications.noItemsMatch': 'No items match your search criteria',
    'medications.startBuildingInventory': 'Start building your inventory by adding your first item',
    'medications.addFirstItem': 'Add First Item',
    'medications.stock': 'Stock',
    'medications.unit': 'Unit',
    'medications.stockLevel': 'Stock Level',
    'medications.expires': 'Expires:',
    'medications.deleteInventoryItem': 'Delete Inventory Item',
    'medications.deleteConfirm': 'Are you sure you want to delete "{{name}}"? This action cannot be undone and will permanently remove this item from your inventory.',
    'medications.deleteItem': 'Delete Item',

    // Appointments
    appointments: 'Appointments',
    addAppointment: 'Add Appointment',
    editAppointment: 'Edit Appointment',
    addNewAppointment: 'Add New Appointment',
    reasonForVisit: 'Reason for visit',
    status: 'Status',
    selectStatus: 'Select status',
    scheduled: 'Scheduled',
    completed: 'Completed',
    cancelled: 'Cancelled',
    createAppointment: 'Create Appointment',
    updateAppointment: 'Update Appointment',
    noAppointmentsFound: 'No appointments found',
    getStartedAppointment: 'Get started by scheduling your first appointment.',
    allScheduledAppointments: 'All Scheduled Appointments',
    fetchDataFailed: 'Failed to fetch data',
    dateRequired: 'Please select a date.',
    appointmentUpdatedSuccess: 'Appointment updated successfully',
    appointmentAddedSuccess: 'Appointment added successfully',
    appointmentSaveFailed: 'Failed to save appointment',
    confirmDeleteAppointment: 'Are you sure you want to delete this appointment?',
    appointmentDeletedSuccess: 'Appointment deleted successfully',
    appointmentDeleteFailed: 'Failed to delete appointment',
    selectPatient: 'Select a patient',
    selectDoctor: 'Select a doctor',
    time: 'Time',

    // Auth
    login: 'Login',
    password: 'Password',
    loginRequired: 'Login Required',
    invalidPassword: 'Invalid Password',
    appShortName: 'CHAMRONGRITH CLINIC',
    hospitalManagementSubtitle: 'Hospital Management',
    language: 'Language',
    logout: 'Logout',
    settings: "Settings",
    profile: "Profile",
    adminName: "Admin Name",
    token: "Token",
    expiresIn: "Expires In",
    reloginToReset: "Relogin to reset expiry to 24h.",
    backup: "Backup",
    exportData: "Export Data (Backup)",
    restoreData: "Restore Data (Paste backup here)",
    backupReady: "Backup ready",
    restoreComplete: "Restore complete",
    restoreFailed: "Restore failed",
    adminInfoSaved: "Admin information saved.",
    authToken: "Auth Token",
    description: "Description",
    enterDescription: "Enter a brief description or notes",
    enterName: "Enter name",
    enterEmail: "Enter email address",
    bloodGroup: "Blood Group",
    view: "View",
    noDocuments: 'No documents available',
    editPatientInformation: 'Edit Patient Information',
    searchPatients: 'Search patients',
    saveChanges: 'Save Changes',
  },
  km: {
    // Navigation
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    patients: 'អ្នកជំងឺ',
    doctors: 'វេជ្ជបណ្ឌិត',
    medications: 'ថ្នាំពេទ្យ',
    prescriptions: 'បទវេជ្ជបញ្ជា',

    // Common
    add: 'បន្ថែម',
    edit: 'កែប្រែ',
    delete: 'លុប',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    name: 'ឈ្មោះ',
    contact: 'ទំនាក់ទំនង',
    search: 'ស្វែងរក',
    print: 'បោះពុម្ព',
    success: 'ជោគជ័យ',
    error: 'បរាជ័យ',

    // Dashboard
    totalPatients: 'អ្នកជំងឺសរុប',
    totalDoctors: 'វេជ្ជបណ្ឌិតសរុប',
    quickActions: 'សកម្មភាពរហ័ស',
    recentActivity: 'សកម្មភាពថ្មីៗ',

    // Patients
    addPatient: 'បន្ថែមអ្នកជំងឺ',
    patientName: 'ឈ្មោះអ្នកជំងឺ',
    age: 'អាយុ',
    medicalHistory: 'ប្រវត្តិវេជ្ជសាស្ត្រ',
    fullName: 'ឈ្មោះ​ពេញ',
    email: 'អ៊ីមែល',
    phoneNumber: 'លេខទូរស័ព្ទ',
    gender: 'ភេទ',
    dateOfBirth: 'ថ្ងៃខែ​ឆ្នាំ​កំណើត',
    address: 'អាសយដ្ឋាន',
    allRegisteredPatients: 'អ្នកជំងឺដែលបានចុះឈ្មោះទាំងអស់',
    noPatientsFound: 'រកមិនឃើញអ្នកជំងឺទេ',
    getStartedPatient: 'ចាប់ផ្តើមដោយបន្ថែមអ្នកជំងឺដំបូងរបស់អ្នក។',
    addNewPatient: 'បន្ថែមអ្នកជំងឺថ្មី',
    editPatient: 'កែសម្រួលអ្នកជំងឺ',
    patientInfoPrompt: 'បញ្ចូលព័ត៌មានរបស់អ្នកជំងឺដើម្បីបង្កើតកំណត់ត្រាថ្មី។',
    selectGender: 'ជ្រើសរើសភេទ',
    male: 'ប្រុស',
    female: 'ស្រី',
    other: 'ផ្សេងទៀត',
    pickDate: 'ជ្រើសរើសកាលបរិច្ឆេទ',
    updatePatient: 'ធ្វើបច្ចុប្បន្នភាពអ្នកជំងឺ',
    createPatient: 'បង្កើតអ្នកជំងឺ',
    patientUpdatedSuccess: 'បានធ្វើបច្ចុប្បន្នភាពអ្នកជំងឺដោយជោគជ័យ',
    patientAddedSuccess: 'បានបន្ថែមអ្នកជំងឺដោយជោគជ័យ',
    patientSaveFailed: 'បរាជ័យក្នុងការរក្សាទុកអ្នកជំងឺ',
    patientDeletedSuccess: 'បានលុបអ្នកជំងឺដោយជោគជ័យ',
    patientDeleteFailed: 'បរាជ័យក្នុងការលុបអ្នកជំងឺ',
    confirmDeletePatient: 'តើអ្នកប្រាកដថាចង់លុបអ្នកជំងឺនេះទេ?',
    fetchPatientsFailed: 'បរាជ័យក្នុងការទាញយកអ្នកជំងឺ',
    loading: 'កំពុងដំណើរការ...',
    actions: 'សកម្មភាព',
    doctorImage: 'រូបវេជ្ជបណ្ឌិត',
    noDoctorAssigned: 'មិនទាន់មានវេជ្ជបណ្ឌិត',
    patientNotFound: 'រកមិនឃើញអ្នកជំងឺ',
    patientNotFoundDescription: 'អ្នកជំងឺដែលអ្នកកំពុងស្វែងរកមិនមានទេ ឬត្រូវបានលុបចេញ។',
    back: 'ត្រឡប់ក្រោយ',
    overview: 'ទិដ្ឋភាពសរុប',
    documents: 'ឯកសារ',
    noDescription: 'មិនមានការពិពណ៌នាទេ',
    noAddress: 'មិនមានអាសយដ្ឋាន',
    emergencyContact: 'ទំនាក់ទំនងបន្ទាន់',
    noEmergencyContact: 'មិនមានព័ត៌មានទំនាក់ទំនងបន្ទាន់',
    upcomingAppointments: 'ការណាត់ជួបខាងមុខ',
    noAppointments: 'មិនមានការណាត់ជួបខាងមុខ',
    noMedicalHistory: 'មិនមានប្រវត្តិវេជ្ជសាស្ត្រទេ',
    assignedDoctor: 'វេជ្ជបណ្ឌិតដែលបានចាត់តាំង',
    bloodType: 'ប្រភេទឈាម',
    selectBloodType: 'ជ្រើសរើសប្រភេទឈាម',
    contactAndInsurance: 'ទំនាក់ទំនង និង ធានារ៉ាប់រង',
    basicInfo: 'ព័ត៌មានមូលដ្ឋាន',
    medical: 'វេជ្ជសាស្ត្រ',
    descriptionPlaceholder: 'ពិពណ៌នាឬកំណត់ចំណាំអំពីអ្នកជំងឺ',
    enterFullName: "បញ្ចូលឈ្មោះពេញរបស់អ្នកជំងឺ",
    preferNotToSay: 'មិនចង់បញ្ជាក់',

    // Doctors
    addDoctor: 'បន្ថែមវេជ្ជបណ្ឌិត',
    doctorName: 'ឈ្មោះវេជ្ជបណ្ឌិត',
    specialty: 'ជំនាញ',
    editDoctor: 'កែសម្រួលវេជ្ជបណ្ឌិត',
    doctorUpdated: 'កែប្រែវេជ្ជបណ្ឌិតបានជោគជ័យ',
    doctorAdded: 'បន្ថែមវេជ្ជបណ្ឌិតបានជោគជ័យ',
    doctorDeleted: 'លុបវេជ្ជបណ្ឌិតបានជោគជ័យ',
    doctorFailedSave: 'បរាជ័យក្នុងការរក្សាទុកវេជ្ជបណ្ឌិត',
    confirmDeleteDoctor: 'តើអ្នកប្រាកដថាចង់លុបវេជ្ជបណ្ឌិតនេះមែនទេ?',
    noDoctorsFound: 'មិនមានវេជ្ជបណ្ឌិត',

    // Medications
    addMedication: 'បន្ថែមថ្នាំពេទ្យ',
    medicationName: 'ឈ្មោះថ្នាំ',
    dosage: 'កម្រិតថ្នាំ',
    stockQuantity: 'បរិមាណស្តុក',
    inStock: 'មានស្តុក',
    lowStock: 'ស្តុកតិច',
    outOfStock: 'អស់ស្តុក',
    medicationUpdatedSuccess: 'បានធ្វើបច្ចុប្បន្នភាពថ្នាំដោយជោគជ័យ',
    medicationAddedSuccess: 'បានបន្ថែមថ្នាំដោយជោគជ័យ',
    medicationSaveFailed: 'បរាជ័យក្នុងការរក្សាទុកថ្នាំ',
    confirmDeleteMedication: 'តើអ្នកប្រាកដថាចង់លុបថ្នាំនេះមែនទេ?',
    medicationDeletedSuccess: 'បានលុបថ្នាំដោយជោគជ័យ',
    medicationDeleteFailed: 'បរាជ័យក្នុងការលុបថ្នាំ',
    fetchMedicationsFailed: 'បរាជ័យក្នុងការទាញយកថ្នាំ',
    noMedicationsFound: 'រកមិនឃើញថ្នាំ',
    getStartedMedication: 'ចាប់ផ្តើមដោយបន្ថែមថ្នាំដំបូងរបស់អ្នក។',
    image: 'រូបភាព',
    uploadImage: 'ផ្ទុករូបភាព',
    // Added for Medications page form/dialog
    'medications.productName': 'ឈ្មោះផលិតផល',
    'medications.category': 'ប្រភេទ',
    'medications.selectCategory': 'ជ្រើសរើសប្រភេទ',
    'medications.other': 'ផ្សេងទៀត',
    'medications.enterNewCategory': 'បញ្ចូលប្រភេទថ្មី',
    'medications.currentStock': 'បរិមាណស្តុកបច្ចុប្បន្ន',
    'medications.unitPrice': 'តម្លៃឯកតា ($)',
    'medications.expiryDate': 'ថ្ងៃផុតកំណត់',
    'medications.productImage': 'រូបភាពផលិតផល',
    'medications.updateItem': 'កែប្រែធាតុ',
    'medications.addItem': 'បន្ថែមធាតុ',
    // Added for Medications page UI
    'medications.inventoryTitle': 'សារពើភ័ណ្ឌថ្នាំ',
    'medications.inventorySubtitle': 'គ្រប់គ្រងស្តុកថ្នាំរបស់អ្នកយ៉ាងមានប្រសិទ្ធភាព',
    'medications.totalValue': 'តម្លៃសរុប',
    'medications.totalItems': 'ចំនួនធាតុសរុប',
    'medications.lowStock': 'ស្តុកតិច',
    'medications.outOfStock': 'អស់ស្តុក',
    'medications.searchPlaceholder': 'ស្វែងរកតាមឈ្មោះ កម្រិតថ្នាំ ឬលេខសម្គាល់...',
    'medications.allCategories': 'ប្រភេទទាំងអស់',
    'medications.status': 'ស្ថានភាព',
    'medications.allStatus': 'ស្ថានភាពទាំងអស់',
    'medications.normalStock': 'ស្តុកធម្មតា',
    'medications.export': 'នាំចេញ',
    'medications.editInventoryItem': 'កែប្រែធាតុសារពើភ័ណ្ឌ',
    'medications.addNewInventoryItem': 'បន្ថែមធាតុសារពើភ័ណ្ឌថ្មី',
    'medications.updateDetails': 'ធ្វើបច្ចុប្បន្នភាពព័ត៌មានសម្រាប់ថ្នាំនេះ។',
    'medications.fillDetails': 'បំពេញព័ត៌មានដើម្បីបន្ថែមថ្នាំថ្មីទៅសារពើភ័ណ្ឌរបស់អ្នក។',
    'medications.noItemsFound': 'រកមិនឃើញធាតុ',
    'medications.noInventoryItems': 'មិនមានធាតុសារពើភ័ណ្ឌ',
    'medications.noItemsMatch': 'មិនមានធាតុដែលផ្គូផ្គងនឹងលក្ខណៈសម្បត្តិស្វែងរករបស់អ្នក',
    'medications.startBuildingInventory': 'ចាប់ផ្តើមបង្កើតសារពើភ័ណ្ឌរបស់អ្នកដោយបន្ថែមធាតុដំបូង',
    'medications.addFirstItem': 'បន្ថែមធាតុដំបូង',
    'medications.stock': 'ស្តុក',
    'medications.unit': 'ឯកតា',
    'medications.stockLevel': 'កម្រិតស្តុក',
    'medications.expires': 'ផុតកំណត់:',
    'medications.deleteInventoryItem': 'លុបធាតុសារពើភ័ណ្ឌ',
    'medications.deleteConfirm': 'តើអ្នកប្រាកដថាចង់លុប "{{name}}"? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ ហើយនឹងលុបធាតុនេះចេញពីសារពើភ័ណ្ឌរបស់អ្នកជាអចិន្ត្រៃយ៍។',
    'medications.deleteItem': 'លុបធាតុ',

    // Appointments
    appointments: 'ការណាត់ជួប',
    addAppointment: 'បន្ថែមការណាត់ជួប',
    editAppointment: 'កែសម្រួលការណាត់ជួប',
    addNewAppointment: 'បន្ថែមការណាត់ជួបថ្មី',
    reasonForVisit: 'មូលហេតុនៃការមកជួប',
    status: 'ស្ថានភាព',
    selectStatus: 'ជ្រើសរើសស្ថានភាព',
    scheduled: 'បានកំណត់ពេល',
    completed: 'បានបញ្ចប់',
    cancelled: 'បានបោះបង់',
    createAppointment: 'បង្កើតការណាត់ជួប',
    updateAppointment: 'ធ្វើបច្ចុប្បន្នភាពការណាត់ជួប',
    noAppointmentsFound: 'រកមិនឃើញការណាត់ជួបទេ',
    getStartedAppointment: 'ចាប់ផ្តើមដោយកំណត់ពេលការណាត់ជួបដំបូងរបស់អ្នក។',
    allScheduledAppointments: 'រាល់ការណាត់ជួបដែលបានកំណត់ពេល',
    fetchDataFailed: 'បរាជ័យក្នុងការទាញយកទិន្នន័យ',
    dateRequired: 'សូមជ្រើសរើសកាលបរិច្ឆេទ។',
    appointmentUpdatedSuccess: 'បានធ្វើបច្ចុប្បន្នភាពការណាត់ជួបដោយជោគជ័យ',
    appointmentAddedSuccess: 'បានបន្ថែមការណាត់ជួបដោយជោគជ័យ',
    appointmentSaveFailed: 'បរាជ័យក្នុងការរក្សាទុកការណាត់ជួប',
    confirmDeleteAppointment: 'តើអ្នកប្រាកដថាចង់លុបការណាត់ជួបនេះមែនទេ?',
    appointmentDeletedSuccess: 'បានលុបការណាត់ជួបដោយជោគជ័យ',
    appointmentDeleteFailed: 'បរាជ័យក្នុងការលុបការណាត់ជួប',
    selectPatient: 'ជ្រើសរើសអ្នកជំងឺ',
    selectDoctor: 'ជ្រើសរើសវេជ្ជបណ្ឌិត',
    time: 'ពេលវេលា',

    // Auth
    login: 'ចូលប្រើប្រាស់',
    password: 'ពាក្យសម្ងាត់',
    loginRequired: 'ត្រូវការចូលប្រើប្រាស់',
    invalidPassword: 'ពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
    appShortName: 'មន្ទីសម្រាកព្យាលបាល​​ ចំរ៉ុងរិទ្ធ',
    saveChanges: 'រក្សាទុកការផ្លាស់ប្តូរ',
    insuranceProvider: 'អ្នកផ្គត់ផ្គង់ធានារ៉ាប់រង',
    hospitalManagementSubtitle: 'ប្រព័ន្ធគ្រប់គ្រងមន្ទីរពេទ្យ',
    language: 'ភាសា',
    logout: 'ចាកចេញ',
    settings: "ការកំណត់",
    profile: "ប្រវត្តិរូប",
    adminName: "ឈ្មោះអ្នកគ្រប់គ្រង",
    token: "Token",
    expiresIn: "ផុតកំណត់ក្នុងរយៈពេល",
    reloginToReset: "ចូលបញ្ចូលឡើងវិញដើម្បីកំណត់ ថ្មីនូវអាយុកាល 24ម៉ោង",
    backup: "បម្រុងទុក",
    exportData: "នាំចេញទិន្នន័យ (បម្រុងទុក)",
    restoreData: "ស្ដារទិន្នន័យ (ដាក់បម្រុងនៅទីនេះ)",
    backupReady: "បានបម្រុងទុក",
    restoreComplete: "ស្ដារទិន្នន័យបានជោគជ័យ",
    restoreFailed: "ស្ដារទិន្នន័យបរាជ័យ",
    adminInfoSaved: "រក្សាទុកព័ត៌មានអ្នកគ្រប់គ្រង។",
    authToken: "សញ្ញាផ្ទៀងផ្ទាត់កម្មសិទ្ធិ",
    description: "ការពិពណ៌នា",
    bloodGroup: "ក្រុមឈាម",
    view: "មើល",
    noDocuments: 'មិនមានឯកសារទេ',
    editPatientInformation: 'កែប្រែព័ត៌មានអ្នកជំងឺ',
    searchPatients: 'ស្វែងរកអ្នកជំងឺ',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'km'>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('hms-language') as 'en' | 'km';
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: 'en' | 'km') => {
    setLanguage(lang);
    localStorage.setItem('hms-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
