import React, { createContext, useContext, useState, useEffect } from 'react';

interface LanguageContextType {
  language: 'en' | 'km';
  setLanguage: (lang: 'en' | 'km') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'common.cancel': 'Cancel',
    dashboard: 'Dashboard',
    patients: 'Patients',
    doctors: 'Doctors',
    medications: 'Medications',
    prescriptions: 'Prescriptions',

    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    name: 'Name',
    contact: 'Contact',
    search: 'Search',
    print: 'Print',
    success: 'Success',
    error: 'Error',
    please: 'Please',

    totalPatients: 'Total Patients',
    totalDoctors: 'Total Doctors',
    quickActions: 'Quick Actions',
    recentActivity: 'Recent Activity',

    addPatient: 'Add Patient',
    patientName: 'Patient Name',
    age: 'Age',
    medicalHistory: 'Medical History',
    fullName: 'Full Name',
    email: 'Email',
    phoneNumber: 'Phone Number',
    gender: 'Gender',
    dateOfBirth: 'Date of Birth',
    address: 'Address',
    allRegisteredPatients: 'All Registered Patients',
    noPatientsFound: 'No patients found.',
    getStartedPatient: 'Get started by adding your first patient.',
    addNewPatient: 'Add New Patient',
    editPatient: 'Edit Patient',
    patientInfoPrompt: "Enter the patient's information to create a new record.",
    selectGender: 'Select gender',
    male: 'Male',
    patientAddedSuccess: 'Patient added successfully',
    patientSaveFailed: 'Failed to save patient',
    patientDeletedSuccess: 'Patient deleted successfully',
    patientDeleteFailed: 'Failed to delete patient',
    confirmDeletePatient: 'Are you sure you want to delete this patient?',
    fetchPatientsFailed: 'Failed to fetch patients',
    actions: 'Actions',
    doctorImage: 'Doctor Image',
    noDoctorAssigned: 'No doctor assigned',
    patientNotFound: 'Patient Not Found',
    patientNotFoundDescription: 'The patient you are looking for does not exist or has been removed.',
    back: 'Back',
    overview: 'Overview',
    documents: 'Documents',
    noDescription: 'No description available',
    noAddress: 'No address provided',
    emergencyContact: 'Emergency Contact',
    noEmergencyContact: 'No emergency contact information',
    upcomingAppointments: 'Upcoming Appointments',
    noAppointments: 'No upcoming appointments',
    noMedicalHistory: 'No medical history recorded',
    assignedDoctor: 'Assigned Doctor',
    bloodType: 'Blood Type',
    selectBloodType: 'Select blood type',
    contactAndInsurance: 'Contact & Insurance',
    basicInfo: 'Basic Info',
    medical: 'Medical',
    descriptionPlaceholder: 'Brief description or notes about the patient',
    enterFullName: "Enter patient's full name",
    preferNotToSay: 'Prefer not to say',

    addDoctor: 'Add Doctor',
    doctorName: 'Doctor Name',
    specialty: 'Specialty',
    editDoctor: 'Edit Doctor',
    doctorUpdated: 'Doctor updated successfully',
    doctorAdded: 'Doctor added successfully',
    doctorDeleted: 'Doctor deleted successfully',
    doctorFailedSave: 'Failed to save doctor',
    confirmDeleteDoctor: 'Are you sure you want to delete this doctor?',
    noDoctorsFound: 'No doctors found',


    addMedication: 'Add Medication',
    medicationName: 'Medication Name',


    female: 'Female',
    other: 'Other',
    pickDate: 'Pick a date',
    updatePatient: 'Update Patient',
    createPatient: 'Create Patient',
    patientUpdatedSuccess: 'Patient updated successfully',
    appointments: 'Appointments',
    addAppointment: 'Add Appointment',
    editAppointment: 'Edit Appointment',
    addNewAppointment: 'Add New Appointment',
    reasonForVisit: 'Reason for visit',
    status: 'Status',
    selectStatus: 'Select status',
    scheduled: 'Scheduled',
    completed: 'Completed',
    cancelled: 'Cancelled',
    createAppointment: 'Create Appointment',
    updateAppointment: 'Update Appointment',
    noAppointmentsFound: 'No appointments found',
    getStartedAppointment: 'Get started by scheduling your first appointment.',
    allScheduledAppointments: 'All Scheduled Appointments',
    fetchDataFailed: 'Failed to fetch data',
    dateRequired: 'Please select a date.',
    appointmentUpdatedSuccess: 'Appointment updated successfully',
    appointmentAddedSuccess: 'Appointment added successfully',
    appointmentSaveFailed: 'Failed to save appointment',
    confirmDeleteAppointment: 'Are you sure you want to delete this appointment?',
    appointmentDeletedSuccess: 'Appointment deleted successfully',
    appointmentDeleteFailed: 'Failed to delete appointment',
    selectPatient: 'Select a patient',
    selectDoctor: 'Select a doctor',
    monthlyTrends: 'Monthly Trends',
    time: 'Time',

    login: 'Login',
    password: 'Password',
    loginRequired: 'Login Required',
    invalidPassword: 'Invalid Password',
    appShortName: 'CHAMRONGRITH CLINIC',
    hospitalManagementSubtitle: 'Hospital Management',
    language: 'Language',
    logout: 'Logout',
    settings: "Settings",
    profile: "Profile",
    adminName: "Admin Name",
    token: "Token",
    expiresIn: "Expires In",
    reloginToReset: "Relogin to reset expiry to 24h.",
    backup: "Backup",
    exportData: "Export Data (Backup)",
    restoreData: "Restore Data (Paste backup here)",
    backupReady: "Backup ready",
    restoreComplete: "Restore complete",
    restoreFailed: "Restore failed",
    adminInfoSaved: "Admin information saved.",
    authToken: "Auth Token",
    description: "Description",
    enterDescription: "Enter a brief description or notes",
    enterName: "Enter name",
    enterEmail: "Enter email address",
    bloodGroup: "Blood Group",
    view: "View",
    noDocuments: 'No documents available',
    editPatientInformation: 'Edit Patient Information',
    searchPatients: 'Search patients',
    saveChanges: 'Save Changes',
    inStock: 'In Stock',
    lowStock: 'Low Stock',
    outOfStock: 'Out of Stock',
    medicationUpdatedSuccess: 'Medication updated successfully',
    medicationAddedSuccess: 'Medication added successfully',
    medicationSaveFailed: 'Failed to save medication',
    confirmDeleteMedication: 'Are you sure you want to delete this medication?',
    medicationDeletedSuccess: 'Medication deleted successfully',
    medicationDeleteFailed: 'Failed to delete medication',
    fetchMedicationsFailed: 'Failed to fetch medications',
    noMedicationsFound: 'No medications found',
    getStartedMedication: 'Get started by adding your first medication.',
    image: 'Image',
    uploadImage: 'Upload Image',
    'medications.productName': 'Product Name',
    'medications.category': 'Category',
    'medications.selectCategory': 'Select category',
    'medications.other': 'Other',
    'medications.enterNewCategory': 'Enter new category',
    'medications.currentStock': 'Current Stock',
    'medications.unitPrice': 'Unit Price ($)',
    'medications.expiryDate': 'Expiry Date',
    'medications.productImage': 'Product Image',
    'medications.updateItem': 'Update Item',
    'medications.addItem': 'Add Item',
    'medications.inventoryTitle': 'Pharmacy Inventory',
    'medications.inventorySubtitle': 'Manage your medication stock efficiently',
    'medications.totalValue': 'Total Value',
    'medications.totalItems': 'Total Items',
    'medications.lowStock': 'Low Stock',
    'medications.outOfStock': 'Out of Stock',
    'medications.searchPlaceholder': 'Search by name, dosage, or SKU...',
    'medications.allCategories': 'All Categories',
    'medications.status': 'Status',
    'medications.allStatus': 'All Status',
    'medications.normalStock': 'Normal Stock',
    'medications.export': 'Export',
    'medications.editInventoryItem': 'Edit Inventory Item',
    'medications.addNewInventoryItem': 'Add New Inventory Item',
    'medications.updateDetails': 'Update the details for this medication.',
    'medications.fillDetails': 'Fill in the details to add a new medication to your inventory.',
    'medications.noItemsFound': 'No items found',
    'medications.noInventoryItems': 'No inventory items',
    'medications.noItemsMatch': 'No items match your search criteria',
    'medications.startBuildingInventory': 'Start building your inventory by adding your first item',
    'medications.addFirstItem': 'Add First Item',
    'medications.stock': 'Stock',
    'medications.unit': 'Unit',
    'medications.stockLevel': 'Stock Level',
    'medications.expires': 'Expires:',
    'medications.deleteInventoryItem': 'Delete Inventory Item',
    'medications.deleteConfirm': 'Are you sure you want to delete "{{name}}"? This action cannot be undone and will permanently remove this item from your inventory.',
    'medications.deleteItem': 'Delete Item',
    'medications.title': 'Medications',
    'medications.subtitle': 'Manage your pharmacy inventory',
    'medications.items': 'items',
    'medications.editMedication': 'Edit Medication',
    'medications.addNewMedication': 'Add New Medication',
    'medications.name': 'Name',
    'medications.dosagePlaceholder': 'e.g., 500mg',
    'medications.antibiotics': 'Antibiotics',
    'medications.painRelief': 'Pain Relief',
    'medications.vitamins': 'Vitamins',
    'medications.noMedicationsFound': 'No medications found',
    'medications.noMedicationsYet': 'No medications yet',
    'medications.noMedicationsMatch': 'No medications match',
    'medications.addFirstMedication': 'Add First Medication',
    'medications.deleteMedication': 'Delete Medication',
    'medications.deleteMedicationConfirm': 'Are you sure you want to delete',
    'medications.medication': 'Medication',
    'common.update': 'Update',
    'common.add': 'Add',

    pos: 'POS',
    'pos.title': 'Point of Sale',
    'pos.subtitle': 'Quick medicine sales and checkout',
    'pos.availableMedicines': 'Available Medicines',
    'pos.searchMedicines': 'Search medicines...',
    'pos.shoppingCart': 'Shopping Cart',
    'pos.customerName': 'Customer Name (Optional)',
    'pos.enterCustomerName': 'Enter customer name...',
    'pos.cartIsEmpty': 'Cart is empty',
    'pos.totalUSD': 'Total (USD):',
    'pos.totalKHR': 'Total (KHR):',
    'pos.exchangeRate': 'Exchange Rate: 1 USD = {{rate}} KHR',
    'pos.completeSale': 'Complete Sale',
    'pos.saleCompleted': 'Sale Completed',
    'pos.receipt': 'Receipt',
    'pos.printReceipt': 'Print Receipt',
    'pos.close': 'Close',
    'pos.successSale': 'Sale completed successfully',
    'pos.cartEmptyError': 'Cart is empty',
    'pos.onlyXInStock': 'Only {{count}} items available in stock',
    'pos.quantity': 'Quantity',
    'pos.unitPrice': 'Unit Price',
    'pos.subtotal': 'Subtotal',
    'pos.date': 'Date',
    'pos.thankYou': 'Thank you for your purchase!',
    'pos.getWellSoon': 'Get well soon!',
    loading: 'Loading',
    'No recent activity found': 'No recent activity found',
    'registered.': 'registered.',
    'Doctor': 'Doctor',
    'added.': 'added.',
    'Medication': 'Medication',
    'Appointment for': 'Appointment for',
    'with Dr.': 'with Dr.',
    'scheduled.': 'scheduled.',
    'System initialized successfully': 'System initialized successfully',
    'Unknown Patient': 'Unknown Patient',
    'Unknown Doctor': 'Unknown Doctor',
    'startMakingSales': 'Start making sales to see them here',
    'noSalesYet': 'No sales recorded yet',
    'noSalesMatch': 'No sales match your search',
    'tryAdjustingSearch': 'Try adjusting your search terms',
    'salesHistory': 'Sales History',
    'viewAndManageSales': 'View and manage your sales transactions',
    'cardView': 'Card View',
    'tableView': 'Table View',
    'salesTransactions': 'Sales Transactions',
    'searchSalesPlaceholder': 'Search by receipt ID, customer name, or medicine...',
    'receiptId': 'Receipt ID',
    'date': 'Date',
    'customer': 'Customer',
    'items': 'Items',
    'totalUSD': 'Total (USD)',
    'totalKHR': 'Total (KHR)',

    'plusMoreItems': '+{count} more items',
    'Sale Details': 'Sale Details',
    'Date & Time': 'Date & Time',
    'Exchange Rate': 'Exchange Rate',
    'Total Items': 'Total Items',
    'Items Purchased': 'Items Purchased',
    'Allergies': 'Allergies',
    'allergiesPlaceholder': 'List any known allergies (medications, food, environmental, etc.)',
    'medicalHistoryPlaceholder': 'Previous medical conditions, surgeries, chronic illnesses, etc.',
    'emergencyContactPlaceholder': 'Emergency contact name and phone number',
    cart: 'Cart',
    clearCart: 'Clear Cart',
    all: 'All',
    addMedicinesToStart: 'Add medicines to start',
    adjustSearchOrCategory: 'Adjust your search or category filters',
    loadingMedications: 'Loading medications...',
    dosage: 'Dosage',
    stockQuantity: 'Stock Quantity',
    unitPrice: 'Unit Price',
    category: 'Category',
    expiryDate: 'Expiry Date',

  },
  km: {
    dashboard: 'ផ្ទាំងគ្រប់គ្រង',
    patients: 'អ្នកជំងឺ',
    doctors: 'វេជ្ជបណ្ឌិត',
    medications: 'ថ្នាំពេទ្យ',
    prescriptions: 'បទវេជ្ជបញ្ជា',

    add: 'បន្ថែម',
    edit: 'កែប្រែ',
    delete: 'លុប',
    save: 'រក្សាទុក',
    cancel: 'បោះបង់',
    name: 'ឈ្មោះ',
    contact: 'ទំនាក់ទំនង',
    search: 'ស្វែងរក',
    print: 'បោះពុម្ព',
    success: 'ជោគជ័យ',
    error: 'បរាជ័យ',
    please: 'សូម',
    saveChanges: 'Save Changes',
    createPatient: 'បង្កើតអ្នកជំងឺ',
    patientUpdatedSuccess: 'បានធ្វើបច្ចុប្បន្នភាពអ្នកជំងឺដោយជោគជ័យ',
    patientAddedSuccess: 'បានបន្ថែមអ្នកជំងឺដោយជោគជ័យ',
    patientSaveFailed: 'បរាជ័យក្នុងការរក្សាទុកអ្នកជំងឺ',
    patientDeletedSuccess: 'បានលុបអ្នកជំងឺដោយជោគជ័យ',
    patientDeleteFailed: 'បរាជ័យក្នុងការលុបអ្នកជំងឺ',
    confirmDeletePatient: 'តើអ្នកប្រាកដថាចង់លុបអ្នកជំងឺនេះទេ?',
    fetchPatientsFailed: 'បរាជ័យក្នុងការទាញយកអ្នកជំងឺ',
    actions: 'សកម្មភាព',
    doctorImage: 'រូបវេជ្ជបណ្ឌិត',
    noDoctorAssigned: 'មិនទាន់មានវេជ្ជបណ្ឌិត',
    patientNotFound: 'រកមិនឃើញអ្នកជំងឺ',
    patientNotFoundDescription: 'អ្នកជំងឺដែលអ្នកកំពុងស្វែងរកមិនមានទេ ឬត្រូវបានលុបចេញ។',
    back: 'ត្រឡប់ក្រោយ',
    overview: 'ទិដ្ឋភាពសរុប',
    documents: 'ឯកសារ',
    noDescription: 'មិនមានការពិពណ៌នាទេ',
    noAddress: 'មិនមានអាសយដ្ឋាន',
    emergencyContact: 'ទំនាក់ទំនងបន្ទាន់',
    noEmergencyContact: 'មិនមានព័ត៌មានទំនាក់ទំនងបន្ទាន់',
    upcomingAppointments: 'ការណាត់ជួបខាងមុខ',
    noAppointments: 'មិនមានការណាត់ជួបខាងមុខ',
    noMedicalHistory: 'មិនមានប្រវត្តិវេជ្ជសាស្ត្រទេ',
    assignedDoctor: 'វេជ្ជបណ្ឌិតដែលបានចាត់តាំង',
    bloodType: 'ប្រភេទឈាម',
    selectBloodType: 'ជ្រើសរើសប្រភេទឈាម',
    contactAndInsurance: 'ទំនាក់ទំនង និង ធានារ៉ាប់រង',
    basicInfo: 'ព័ត៌មានមូលដ្ឋាន',
    medical: 'វេជ្ជសាស្ត្រ',
    descriptionPlaceholder: 'ពិពណ៌នាឬកំណត់ចំណាំអំពីអ្នកជំងឺ',
    enterFullName: "បញ្ចូលឈ្មោះពេញរបស់អ្នកជំងឺ",
    preferNotToSay: 'មិនចង់បញ្ជាក់',

    addDoctor: 'បន្ថែមវេជ្ជបណ្ឌិត',
    doctorName: 'ឈ្មោះវេជ្ជបណ្ឌិត',
    specialty: 'ជំនាញ',
    editDoctor: 'កែសម្រួលវេជ្ជបណ្ឌិត',
    doctorUpdated: 'កែប្រែវេជ្ជបណ្ឌិតបានជោគជ័យ',
    doctorAdded: 'បន្ថែមវេជ្ជបណ្ឌិតបានជោគជ័យ',
    doctorDeleted: 'លុបវេជ្ជបណ្ឌិតបានជោគជ័យ',
    doctorFailedSave: 'បរាជ័យក្នុងការរក្សាទុកវេជ្ជបណ្ឌិត',
    confirmDeleteDoctor: 'តើអ្នកប្រាកដថាចង់លុបវេជ្ជបណ្ឌិតនេះមែនទេ?',
    noDoctorsFound: 'មិនមានវេជ្ជបណ្ឌិត',

    addMedication: 'បន្ថែមថ្នាំពេទ្យ',
    medicationName: 'ឈ្មោះថ្នាំ',
    dosage: 'កម្រិតថ្នាំ',
    stockQuantity: 'បរិមាណស្តុក',
    inStock: 'មានស្តុក',
    lowStock: 'ស្តុកតិច',
    outOfStock: 'អស់ស្តុក',
    medicationUpdatedSuccess: 'បានធ្វើបច្ចុប្បន្នភាពថ្នាំដោយជោគជ័យ',
    medicationAddedSuccess: 'បានបន្ថែមថ្នាំដោយជោគជ័យ',
    medicationSaveFailed: 'បរាជ័យក្នុងការរក្សាទុកថ្នាំ',
    confirmDeleteMedication: 'តើអ្នកប្រាកដថាចង់លុបថ្នាំនេះមែនទេ?',
    medicationDeletedSuccess: 'បានលុបថ្នាំដោយជោគជ័យ',
    medicationDeleteFailed: 'បរាជ័យក្នុងការលុបថ្នាំ',
    fetchMedicationsFailed: 'បរាជ័យក្នុងការទាញយកថ្នាំ',
    noMedicationsFound: 'រកមិនឃើញថ្នាំ',
    getStartedMedication: 'ចាប់ផ្តើមដោយបន្ថែមថ្នាំដំបូងរបស់អ្នក។',
    image: 'រូបភាព',
    uploadImage: 'ផ្ទុករូបភាព',
    'medications.productName': 'ឈ្មោះផលិតផល',
    'medications.category': 'ប្រភេទ',
    'medications.selectCategory': 'ជ្រើសរើសប្រភេទ',
    'medications.other': 'ផ្សេងទៀត',
    'common.cancel':  'បោះបង់',
    'medications.enterNewCategory': 'បញ្ចូលប្រភេទថ្មី',
    'medications.currentStock': 'បរិមាណស្តុកបច្ចុប្បន្ន',
    'medications.unitPrice': 'តម្លៃឯកតា ($)',
    'confirmPassword': 'បញ្ជាក់ពាក្យសម្ងាត់',
    'medications.expiryDate': 'ថ្ងៃផុតកំណត់',
    'medications.productImage': 'រូបភាពផលិតផល',
    'medications.updateItem': 'កែប្រែធាតុ',
    'medications.addItem': 'បន្ថែមធាតុ',
    'medications.inventoryTitle': 'សារពើភ័ណ្ឌថ្នាំ',
    'medications.inventorySubtitle': 'គ្រប់គ្រងស្តុកថ្នាំរបស់អ្នកយ៉ាងមានប្រសិទ្ធភាព',
    'medications.totalValue': 'តម្លៃសរុប',
    'medications.totalItems': 'ចំនួនធាតុសរុប',
    'medications.lowStock': 'ស្តុកតិច',
    'medications.outOfStock': 'អស់ស្តុក',
    'medications.searchPlaceholder': 'ស្វែងរកតាមឈ្មោះ កម្រិតថ្នាំ ឬលេខសម្គាល់...',
    'medications.allCategories': 'ប្រភេទទាំងអស់',
    'medications.status': 'ស្ថានភាព',
    'medications.allStatus': 'ស្ថានភាពទាំងអស់',
    'medications.normalStock': 'ស្តុកធម្មតា',
    'medications.export': 'នាំចេញ',
    'medications.editInventoryItem': 'កែប្រែធាតុសារពើភ័ណ្ឌ',
    'medications.addNewInventoryItem': 'បន្ថែមធាតុសារពើភ័ណ្ឌថ្មី',
    'medications.updateDetails': 'ធ្វើបច្ចុប្បន្នភាពព័ត៌មានសម្រាប់ថ្នាំនេះ។',
    'medications.fillDetails': 'បំពេញព័ត៌មានដើម្បីបន្ថែមថ្នាំថ្មីទៅសារពើភ័ណ្ឌរបស់អ្នក។',
    'medications.noItemsFound': 'រកមិនឃើញធាតុ',
    'medications.noInventoryItems': 'មិនមានធាតុសារពើភ័ណ្ឌ',
    'medications.noItemsMatch': 'មិនមានធាតុដែលផ្គូផ្គងនឹងលក្ខណៈសម្បត្តិស្វែងរករបស់អ្នក',
    'medications.startBuildingInventory': 'ចាប់ផ្តើមបង្កើតសារពើភ័ណ្ឌរបស់អ្នកដោយបន្ថែមធាតុដំបូង',
    'medications.addFirstItem': 'បន្ថែមធាតុដំបូង',
    'medications.stock': 'ស្តុក',
    'medications.unit': 'ឯកតា',
    'medications.stockLevel': 'កម្រិតស្តុក',
    'medications.expires': 'ផុតកំណត់:',
    'medications.deleteInventoryItem': 'លុបធាតុសារពើភ័ណ្ឌ',
    'medications.deleteConfirm': 'តើអ្នកប្រាកដថាចង់លុប "{{name}}"? សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ ហើយនឹងលុបធាតុនេះចេញពីសារពើភ័ណ្ឌរបស់អ្នកជាអចិន្ត្រៃយ៍។',
    'medications.deleteItem': 'លុបធាតុ',
    'medications.title': 'ថ្នាំ',
    'medications.subtitle': 'គ្រប់គ្រងសារពើភ័ណ្ឌថ្នាំរបស់អ្នក',
    'medications.items': 'ធាតុ',
    'medications.editMedication': 'កែប្រែថ្នាំ',
    'medications.addNewMedication': 'បន្ថែមថ្នាំថ្មី',
    'medications.name': 'ឈ្មោះ',
    'medications.dosagePlaceholder': 'ឧ. ៥០០មីលីក្រាម',
    'medications.antibiotics': 'ថ្នាំប្រឆាំងមេរោគ',
    'medications.painRelief': 'ថ្នាំបំបាត់ការឈឺ',
    'medications.vitamins': 'វីតាមីន',
    'medications.noMedicationsFound': 'រកមិនឃើញថ្នាំ',
    'medications.noMedicationsYet': 'មិនទាន់មានថ្នាំ',
    'medications.noMedicationsMatch': 'មិនមានថ្នាំដែលផ្គូផ្គង',
    'medications.addFirstMedication': 'បន្ថែមថ្នាំដំបូង',
    'medications.deleteMedication': 'លុបថ្នាំ',
    'medications.deleteMedicationConfirm': 'តើអ្នកប្រាកដថាចង់លុប',
    'medications.medication': 'ថ្នាំ',
    'common.update': 'កែប្រែ',
    'common.add': 'បន្ថែម',

    appointments: 'ការណាត់ជួប',
    addAppointment: 'បន្ថែមការណាត់ជួប',
    editAppointment: 'កែសម្រួលការណាត់ជួប',
    addNewAppointment: 'បន្ថែមការណាត់ជួបថ្មី',
    reasonForVisit: 'មូលហេតុនៃការមកជួប',
    status: 'ស្ថានភាព',
    selectStatus: 'ជ្រើសរើសស្ថានភាព',
    scheduled: 'បានកំណត់ពេល',
    completed: 'បានបញ្ចប់',
    cancelled: 'បានបោះបង់',
    createAppointment: 'បង្កើតការណាត់ជួប',
    updateAppointment: 'ធ្វើបច្ចុប្បន្នភាពការណាត់ជួប',
    noAppointmentsFound: 'រកមិនឃើញការណាត់ជួបទេ',
    getStartedAppointment: 'ចាប់ផ្តើមដោយកំណត់ពេលការណាត់ជួបដំបូងរបស់អ្នក។',
    allScheduledAppointments: 'រាល់ការណាត់ជួបដែលបានកំណត់ពេល',
    fetchDataFailed: 'បរាជ័យក្នុងការទាញយកទិន្នន័យ',
    dateRequired: 'សូមជ្រើសរើសកាលបរិច្ឆេទ។',
    appointmentUpdatedSuccess: 'បានធ្វើបច្ចុប្បន្នភាពការណាត់ជួបដោយជោគជ័យ',
    appointmentAddedSuccess: 'បានបន្ថែមការណាត់ជួបដោយជោគជ័យ',
    appointmentSaveFailed: 'បរាជ័យក្នុងការរក្សាទុកការណាត់ជួប',
    confirmDeleteAppointment: 'តើអ្នកប្រាកដថាចង់លុបការណាត់ជួបនេះមែនទេ?',
    appointmentDeletedSuccess: 'បានលុបការណាត់ជួបដោយជោគជ័យ',
    appointmentDeleteFailed: 'បរាជ័យក្នុងការលុបការណាត់ជួប',
    selectPatient: 'ជ្រើសរើសអ្នកជំងឺ',
    selectDoctor: 'ជ្រើសរើសវេជ្ជបណ្ឌិត',
    time: 'ពេលវេលា',
    monthlyTrends: 'ប្រតិបត្តិការប្រចាំខែ',
    login: 'ចូលប្រើប្រាស់',
    password: 'ពាក្យសម្ងាត់',
    loginRequired: 'ត្រូវការចូលប្រើប្រាស់',
    invalidPassword: 'ពាក្យសម្ងាត់មិនត្រឹមត្រូវ',
    appShortName: 'មន្ទីសម្រាកព្យាលបាល​​ ចំរ៉ុងរិទ្ធ',

    totalPatients: 'អ្នកជំងឺសរុប',
    totalDoctors: 'វេជ្ជបណ្ឌិតសរុប',
    quickActions: 'សកម្មភាពរហ័ស',
    recentActivity: 'សកម្មភាពថ្មីៗ',

    addPatient: 'បន្ថែមអ្នកជំងឺ',
    patientName: 'ឈ្មោះអ្នកជំងឺ',
    age: 'អាយុ',
    medicalHistory: 'ប្រវត្តិវេជ្ជសាស្ត្រ',
    fullName: 'ឈ្មោះ​ពេញ',
    email: 'អ៊ីមែល',
    phoneNumber: 'លេខទូរស័ព្ទ',
    gender: 'ភេទ',
    dateOfBirth: 'ថ្ងៃខែ​ឆ្នាំ​កំណើត',
    address: 'អាសយដ្ឋាន',
    allRegisteredPatients: 'អ្នកជំងឺដែលបានចុះឈ្មោះទាំងអស់',
    noPatientsFound: 'រកមិនឃើញអ្នកជំងឺទេ។',
    getStartedPatient: 'ចាប់ផ្តើមដោយបន្ថែមអ្នកជំងឺដំបូងរបស់អ្នក។',
    addNewPatient: 'បន្ថែមអ្នកជំងឺថ្មី',
    editPatient: 'កែសម្រួលអ្នកជំងឺ',
    patientInfoPrompt: 'បញ្ចូលព័ត៌មានរបស់អ្នកជំងឺដើម្បីបង្កើតកំណត់ត្រាថ្មី។',
    selectGender: 'ជ្រើសរើសភេទ',
    male: 'ប្រុស',
    female: 'ស្រី',
    other: 'ផ្សេងទៀត',
    pickDate: 'ជ្រើសរើសកាលបរិច្ឆេទ',
    updatePatient: 'ធ្វើបច្ចុប្បន្នភាពអ្នកជំងឺ',
    hospitalManagementSubtitle: 'ការគ្រប់គ្រងមន្ទីរពេទ្យ',
    language: 'ភាសា',
    logout: 'ចាកចេញ',
    settings: 'ការកំណត់',
    profile: 'ប្រវត្តិរូប',
    adminName: 'ឈ្មោះអ្នកគ្រប់គ្រង',
    token: 'សញ្ញាសម្ងាត់',
    expiresIn: 'ផុតកំណត់ក្នុង',
    reloginToReset: 'ចូលឡើងវិញដើម្បីកំណត់ពេលផុតកំណត់ទៅ ២៤ម៉ោងវិញ។',
    backup: 'បម្រុងទុក',
    exportData: 'នាំចេញទិន្នន័យ (បម្រុងទុក)',
    restoreData: 'ស្ដារទិន្នន័យ (បិទភ្ជាប់បម្រុងទុកនៅទីនេះ)',
    backupReady: 'បម្រុងទុករួចរាល់',
    restoreComplete: 'ស្ដារទិន្នន័យរួចរាល់',
    restoreFailed: 'បរាជ័យក្នុងការស្ដារទិន្នន័យ',
    adminInfoSaved: 'បានរក្សាទុកព័ត៌មានអ្នកគ្រប់គ្រង',
    authToken: 'សញ្ញាសម្ងាត់',
    description: 'ការពិពណ៌នា',
    enterDescription: 'បញ្ចូលការពិពណ៌នាឬកំណត់ចំណាំ',
    enterName: 'បញ្ចូលឈ្មោះ',
    enterEmail: 'បញ្ចូលអាសយដ្ឋានអ៊ីមែល',
    bloodGroup: 'ក្រុមឈាម',
    view: 'មើល',
    noDocuments: 'មិនមានឯកសារ',
    editPatientInformation: 'កែសម្រួលព័ត៌មានអ្នកជំងឺ',
    searchPatients: 'ស្វែងរកអ្នកជំងឺ',

    pos: 'POS',
    'pos.title': 'ប្រព័ន្ធលក់',
    'pos.subtitle': 'លក់ថ្នាំ និងគិតលុយយ៉ាងឆាប់រហ័ស',
    'pos.availableMedicines': 'ថ្នាំដែលមាន',
    'pos.searchMedicines': 'ស្វែងរកថ្នាំ...',
    'pos.shoppingCart': 'រទេះទំនិញ',
    'pos.customerName': 'ឈ្មោះអតិថិជន (ស្រេចចិត្ត)',
    'pos.enterCustomerName': 'បញ្ចូលឈ្មោះអតិថិជន...',
    'pos.cartIsEmpty': 'រទេះទំនិញទទេ',
    'pos.totalUSD': 'សរុប (USD):',
    'pos.totalKHR': 'សរុប (KHR):',
    'pos.exchangeRate': 'អត្រាប្តូរប្រាក់: 1 USD = {{rate}} KHR',
    'pos.completeSale': 'បញ្ចប់ការលក់',
    'pos.saleCompleted': 'បានបញ្ចប់ការលក់',
    'pos.receipt': 'បង្កាន់ដៃ',
    'pos.printReceipt': 'បោះពុម្ពបង្កាន់ដៃ',
    'pos.close': 'បិទ',
    'pos.successSale': 'បានបញ្ចប់ការលក់ដោយជោគជ័យ',
    'pos.cartEmptyError': 'រទេះទំនិញទទេ',
    'pos.onlyXInStock': 'មានតែ {{count}} ធាតុប៉ុណ្ណោះនៅក្នុងស្តុក',
    'pos.quantity': 'បរិមាណ',
    'pos.unitPrice': 'តម្លៃឯកតា',
    'pos.subtotal': 'សរុបរង',
    'pos.date': 'កាលបរិច្ឆេទ',
    'pos.thankYou': 'សូមអរគុណសម្រាប់ការទិញរបស់អ្នក!',
    'pos.getWellSoon': 'សូមឲ្យមានសុខភាពល្អវិញ!',

    loading: 'កំពុងផ្ទុក',
    'No recent activity found': 'រកមិនឃើញសកម្មភាពថ្មីៗ',
    'registered.': 'បានចុះឈ្មោះ។',
    'Doctor': 'វេជ្ជបណ្ឌិត',
    'added.': 'បានបន្ថែម។',
    'Medication': 'ថ្នាំ',
    'Appointment for': 'ការណាត់ជួបសម្រាប់',
    'with Dr.': 'ជាមួយវេជ្ជបណ្ឌិត',
    'scheduled.': 'បានកំណត់ពេល។',
    'System initialized successfully': 'ប្រព័ន្ធបានចាប់ផ្តើមដោយជោគជ័យ',
    'Unknown Patient': 'មិនស្គាល់អ្នកជំងឺ',
    'Unknown Doctor': 'មិនស្គាល់វេជ្ជបណ្ឌិត',
    'startMakingSales': 'ចាប់ផ្តើមលក់ដើម្បីឃើញនៅទីនេះ',
    'noSalesYet': 'មិនទាន់មានប្រតិបត្តិការលក់',
    'noSalesMatch': 'មិនមានប្រតិបត្តិការលក់ដែលផ្គូផ្គង',
    'tryAdjustingSearch': 'សូមសាកល្បងផ្លាស់ប្តូរការស្វែងរក',
    'salesHistory': 'ប្រវត្តិការលក់',
    'viewAndManageSales': 'មើល និងគ្រប់គ្រងប្រតិបត្តិការលក់របស់អ្នក',
    'cardView': 'មើលជាកាត',
    'tableView': 'មើលជាតារាង',
    'salesTransactions': 'ប្រតិបត្តិការលក់',
    'searchSalesPlaceholder': 'ស្វែងរកតាមលេខបង្កាន់ដៃ ឈ្មោះអតិថិជន ឬថ្នាំ...',
    'receiptId': 'លេខបង្កាន់ដៃ',
    'date': 'កាលបរិច្ឆេទ',
    'customer': 'អតិថិជន',
    'items': 'ធាតុ',
    'totalUSD': 'សរុប (USD)',
    'totalKHR': 'សរុប (KHR)',
    totalSales: 'ចំនួនលក់សរុប',
    totalRevenue: 'ប្រាក់ចំណូលសរុប',
    itemsSold: 'ចំនួនទំនិញបានលក់',
    averageSale: 'លក់មធ្យម',
    saleDetails: 'ព័ត៌មានលម្អិតអំពីការលក់',
    itemsPurchased: 'ទំនិញដែលបានទិញ',
    dateAndTime: 'កាលបរិច្ឆេទ និងម៉ោង',
    exchangeRate: 'អត្រាប្តូរប្រាក់',
    totalItems: 'ចំនួនសរុប',
    printReceipt: 'បោះពុម្ពបង្កាន់ដៃ',
    close: 'បិទ',
    plusMoreItems: '+{count} ទំនិញបន្ថែម',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<'en' | 'km'>('en');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('hms-language') as 'en' | 'km';
    if (savedLanguage) {
      setLanguage(savedLanguage);
    }
  }, []);

  const handleSetLanguage = (lang: 'en' | 'km') => {
    setLanguage(lang);
    localStorage.setItem('hms-language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
